version: "3.3"

networks:
  traefik:
    external: true

services:
  traefik:
    container_name: traefik
    image: traefik:latest
    networks:
      - traefik
    ports:
      - 8080:80 # Entrypoint web
      - 8443:443 # Entrypoint websecure
      #- 8081:8080 # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./conf:/etc/traefik/
      - ./acme.json:/acme.json
      #- ./clientAuth_CA.crt:/clientAuth_CA.crt:ro
    restart: unless-stopped
