version: '2.2'

services:
  openhab:
    image: "openhab/openhab:stable"
    restart: always
    network_mode: host
    volumes:
      - "./addons:/openhab/addons"
      - "./conf:/openhab/conf"
      - "./userdata:/openhab/userdata"
    environment:
      OPENHAB_HTTP_PORT: "15000" # I have closed this ports by a firewall.
      OPENHAB_HTTPS_PORT: "15001" # I have closed this ports by a firewall.
      EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/Berlin"
      LC_ALL: "de_DE.UTF-8"
      LANG: "de_DE.UTF-8"
      LANGUAGE: "de_DE.UTF-8"
      
