## Static configuration
[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.http.redirections.entryPoint]
      to = "https"
      scheme = "https"

  [entryPoints.https]
    address = ":443"

[api]
  dashboard = true
  insecure = true

[certificatesResolvers.lets-encrypt.acme]
  email = "admin@your_domain" # Replace your_domain with your real domain
  storage = "acme.json"
  [certificatesResolvers.lets-encrypt.acme.tlsChallenge]

[providers.docker]
  watch = true
  network = "traefik"
  exposedByDefault = false

[providers.file]
  directory = "/etc/traefik/dynamic"
  watch = true

[serversTransport]
  insecureSkipVerify = true

[log]
  level = "warn"
