# Running InfluxDB 2.x
version: "3.3"
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    hostname: influxdb
    volumes:
      - ./influxdb/data:/var/lib/influxdb2:rw
      - ./influxdb/conf:/etc/influxdb2:ro
      #- ./influxdb/ssl_certs:/etc/ssl/certs # Run update-ca-certificates
    ports:
      - 8086:8086
    environment:
      #- INFLUXD_TLS_CERT=/etc/influxdb2/ssl/influxdb.crt
      #- INFLUXD_TLS_KEY=/etc/influxdb2/ssl/influxdb.pem
    restart: unless-stopped
# Running Telegraf
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    hostname: telegraf
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    restart: unless-stopped

# Running latest Grafana on Alpine Linux. 
# https://grafana.com/docs/grafana/latest/administration/configure-docker/
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    hostname: grafana
    volumes:
      - ./grafana/data:/var/lib/grafana:rw
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      #- ./grafana/provisioning:/etc/grafana/provisioning:ro
    user: "1026" # Run "id -u" to get your user id on the Docker host
    depends_on:
      - influxdb
    ports:
      - 3001:3000
    environment:
      # Override settings in grafana.ini
      - GF_DEFAULT_INSTANCE_NAME=DS918plus
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_NAME=openHAB
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      # Install plugins here
      # - GF_INSTALL_PLUGINS="list of plugins seperated by ,"
    restart: unless-stopped