# Note: If you encounter any permission issues, set the correct permissions:
# chown -R nginx-swag:users config
# chmod -R a=,a+rX,u+w,g+w config
# This sets folders to 775 and files to 664, and ensures correct ownership.
# See: https://github.com/linuxserver/docker-swag/issues/347

version: "3.3"

networks:
  traefik:
    external: true

services:
  swag:
    # Releases: https://github.com/linuxserver/docker-swag/releases
    image: linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    networks:
      - traefik
    environment:
      # Get uid & gid by running id username
      - PUID=1046
      - PGID=100
      - TZ=Europe/Berlin
      - URL= # Insert your DuckDNS domain here
      - SUBDOMAINS=wildcard # DuckDNS certs support subdomain wildcadrs
      - VALIDATION=duckdns
      - DNSPLUGIN=duckdns # Use DuckDNS as dynamic DNS service
      - DUCKDNSTOKEN= # Insert your DuckDNS token here
      - ONLY_SUBDOMAINS=true # DuckDNS certs for subdomain wildcards oviously only support subdomains
      - DOCKER_MODS=linuxserver/mods:swag-dashboard|linuxserver/mods:swag-dbip|linuxserver/mods:swag-auto-reload
      - WATCHLIST="/config/nginx|/config/nginx/proxy-confs"
    volumes:
      - ./config:/config
    ports:
      - 8443:443
    restart: always
