version: "3.3"

networks:
  traefik:
    external: true
  internal:
    external: false

services:
# Running InfluxDB 2.x
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    hostname: influxdb
    networks:
      - internal
    volumes:
      - ./influxdb/data:/var/lib/influxdb2:rw
      - ./influxdb/conf:/etc/influxdb2:ro
      # Enable internal TLS
      #- ./influxdb/ssl_certs:/etc/ssl/certs # Run update-ca-certificates
      #- ./influxdb/influxdb.crt:/etc/ssl/influxdb.crt:ro
      #- ./influxdb/influxdb.pem:/etc/ssl/private/influxdb.pem:ro
    ports:
      # - 8086:8086 # InfluxDB internal TLS
      - 8087:8086 # External Reverse Proxy for TLS
    #environment: # Enable internal TLS
      #- INFLUXD_TLS_CERT=/etc/ssl/influxdb.crt:ro
      #- INFLUXD_TLS_KEY=/etc/ssl/private/influxdb.pem:ro
    restart: unless-stopped
# Running Telegraf
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    hostname: telegraf
    networks:
      - internal
    volumes:
      -  /var/run/docker.sock:/var/run/docker.sock:ro
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    restart: unless-stopped

# Running latest Grafana on Alpine Linux. 
# https://grafana.com/docs/grafana/latest/administration/configure-docker/
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    hostname: grafana
    networks:
      - internal
      - traefik
    volumes:
      - ./grafana/data:/var/lib/grafana:rw
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
    user: "1026" # Run "id -u" to get your user id on the Docker host
    depends_on:
      - influxdb
    ports:
      - 3000:3000
    environment:
      # Override settings in grafana.ini
      - GF_DEFAULT_INSTANCE_NAME=DS918plus
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_NAME=openHAB
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      # Install plugins here
      # - GF_INSTALL_PLUGINS="list of plugins seperated by ,"
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host(`grafana.your_domain`)
      - traefik.http.routers.grafana.tls=true
      - traefik.http.routers.grafana.entrypoints=https
      - traefik.http.routers.grafana.tls.certresolver=lets-encrypt
      - traefik.http.routers.grafana.middlewares=secHeaders@file
    restart: unless-stopped
