# https://github.com/ludeeus/action-shellcheck

name: ShellCheck

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    paths:
      - 'backup_restore.bash'
      - '.github/workflows/shellcheck-action.yml'
  pull_request:
    paths:
      - 'backup_restore.bash'
      - '.github/workflows/shellcheck-action.yml'

jobs:
  build:
    name: ShellCheck
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@master
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      env:
        SHELLCHECK_OPTS: -e SC1017
